name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - common
jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3
        with:
          pr-mode: false
          results-dir: /home/runner/work/_temp/qodana/results
          cache-dir: /home/runner/work/_temp/qodana/caches
          use-caches: true
          primary-cache-key: qodana-2024.3-refs/pull/21/merge-6056b46607574e34466146f1c714e262b33f86ba
          additional-cache-key: qodana-2024.3-refs/pull/21/merge
          cache-default-branch-only: false
          upload-result: false
          artifact-name: qodana-report
          use-annotations: true
          post-pr-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-fixes: none
          commit-message: 🤖 Apply quick-fixes by Qodana
          use-nightly: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
